### ISSUE TITLE
Crash on dedicated server

### ISSUE THREAD

**Issue by TomKauffeld** [ProjectET/Deep-Mob-Learning-Simulacrum#8]
Our dedicated server crashes as soon as someone connects and loads the affected chunk with the following report
[crash report.txt](https://github.com/ProjectET/Deep-Mob-Learning-Simulacrum/files/7272984/crash.report.txt)

**Comment by ProjectET** [comment]
Update to 1.0.3 on curseforge. It is a simple drop in replacement on the server.
